
version: '2.3'
services:
  # nvidia:
  #   image: nvidia/cuda
  #   runtime: nvidia
  #   command: nvidia-smi
# Varun
  varun:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "1002:22"
      - "1003:5920"
    volumes:
      - /media/hdd/varun:/home/varun
      - /media/ssda/varun:/mnt/ssd/
    tty: true
    stdin_open: true
    environment:
      - USERNAME=varun

  varun_torch:
    image: iitmcvg/torch
    runtime: nvidia
    command: bash
    ports:
      - "3002:22"
      - "3003:5920"
    volumes:
      - /media/hdd/varun:/home/varun/
      - /media/ssda/varun:/mnt/ssd/
    tty: true
    stdin_open: true
    environment:
      - USERNAME=varun 

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - /media/hdd:/data
      - /media/minio_config:/root/.minio 
    tty: true
    stdin_open: false
    environment:
      - TZ="Asia/Kolkata"
      - "MINIO_SECRET_KEY=iitmcvg/minio/msi_HDD"
      - "MINIO_ACCESS_KEY=iitmcvg"

# Anand
  holojest:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "2002:22"
      - "2003:5920"
    volumes:
      - /media/hdd/holojest:/home/holojest
      - /media/ssda/holojest:/mnt/ssd
    tty: true
    stdin_open: true
    environment:
      - USERNAME=holojest
