version: '2.3'
services:
  # nvidia:
  #   image: nvidia/cuda
  #   runtime: nvidia
  #   command: nvidia-smi
# Varun
  varun:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "1002:22"
      - "1003:5900"
    volumes:
      - /media/home/varun:/home/varun
      - /mnt/ssda/varun:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=varun

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - /media/iitmcvg/VARUN_CVI:/data
      - /mnt/config:/root/.minio 
    tty: true
    stdin_open: false
    environment:
      - TZ="Asia/Kolkata"
      - "MINIO_SECRET_KEY=iitmcvg/minio/usb1"
      - "MINIO_ACCESS_KEY=iitmcvg"

# Muthu
  aravinth:
    image: iitmcvg/openpose
    runtime: nvidia
    command: bash
    ports:
      - "6002:22"
      - "6003:5901"
    volumes:
      - /media/home/aravinth:/home/aravinth
      - /mnt/ssda/aravinth:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=aravinth

# Anand
  anand:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "9002:22"
      - "9003:5920"
    volumes:
      - /media/home/anand:/home/anand
      - /mnt/ssda/anand:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=anand

# Sumanth
  sumanth:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "4002:22"
      - "4003:5920"
    volumes:
      - /media/home/sumanth:/home/vighnesh
      - /mnt/ssda/sumanth:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=sumanth

# Vighnesh
  vighnesh:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "14002:22"
      - "14003:5920"
    volumes:
      - /media/home/vignesh:/home/vighnesh
      - /mnt/ssda/vignesh:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=vighnesh

  varun_torch:
    image: iitmcvg/torch
    runtime: nvidia
    command: bash
    ports:
      - "1004:22"
    volumes:
      - /media/home/varun:/home/varun
      - /mnt/ssda/varun:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=varun

# SLAM
  slam:
    image: iitmcvg/workstation-x11
    runtime: nvidia
    command: bash
    ports:
      - "15002:22"
      - "15003:5920"
    volumes:
      - /media/home/slam:/home/slam
      - /mnt/ssda/slam:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    tty: true
    stdin_open: true
    environment:
      - USERNAME=slam
      - DISPLAY=10.21.18.200:20
      - XAUTHORITY=/tmp/.docker.xauth

# Harsha
  harsha:
    image: iitmcvg/workstation
    runtime: nvidia
    command: bash
    ports:
      - "16002:22"
      - "16003:5900"
    volumes:
      - /media/home/harsha:/home/varun
      - /mnt/ssda/harsha:/mnt/ssd
      - /media/iitmcvg/VARUN_CVI:/mnt/dataset_HDD
      - /media/hdd2:/mnt/checkpoints_HDD
    tty: true
    stdin_open: true
    environment:
      - USERNAME=harsha



